export const GET_ALL_MOVIES_REQUEST = 'GET_ALL_MOVIES_REQUEST';
export const GET_ALL_MOVIES_SUCCESS = 'GET_ALL_MOVIES_SUCCESS';
export const GET_ALL_MOVIES_FAIL = 'GET_ALL_MOVIES_FAIL';

export const ADD_LIKE_BY_CURRENT_USER = 'ADD_LIKE_BY_CURRENT_USER'
export const ADD_DISLIKE_BY_CURRENT_USER = 'ADD_DISLIKE_BY_CURRENT_USER'

export const DELETE_A_MOVIE = 'DELETE_A_MOVIE'

